const fs = require('fs');
const path = require('path');
const sqlite3 = require('sqlite3').verbose();
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function createDirectories() {
  console.log('Creating necessary directories...');
  const dirs = ['./data', './uploads', './logs', './src/services', './src/routes', './src/models', './src/middleware'];
  
  dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`✓ Created directory: ${dir}`);
    } else {
      console.log(`✓ Directory exists: ${dir}`);
    }
  });
}

async function setupEnvironment() {
  console.log('\n=== Environment Setup ===');
  
  if (fs.existsSync('.env')) {
    const overwrite = await question('.env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Skipping environment setup.');
      return;
    }
  }
  
  console.log('Let\'s set up your environment variables...\n');
  
  const port = await question('Server port (default: 3000): ') || '3000';
  
  console.log('\n--- X (Twitter) API Configuration ---');
  console.log('Get these from: https://developer.twitter.com/');
  const twitterApiKey = await question('Twitter API Key: ');
  const twitterApiSecret = await question('Twitter API Secret: ');
  const twitterAccessToken = await question('Twitter Access Token: ');
  const twitterAccessTokenSecret = await question('Twitter Access Token Secret: ');
  
  console.log('\n--- LinkedIn API Configuration ---');
  console.log('Get these from: https://developer.linkedin.com/');
  const linkedinClientId = await question('LinkedIn Client ID: ');
  const linkedinClientSecret = await question('LinkedIn Client Secret: ');
  
  const sessionSecret = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
  
  const envContent = `# Environment Configuration
# Generated by setup script on ${new Date().toISOString()}

# Server Configuration
PORT=${port}
NODE_ENV=development

# X (Twitter) API Configuration
TWITTER_API_KEY=${twitterApiKey}
TWITTER_API_SECRET=${twitterApiSecret}
TWITTER_ACCESS_TOKEN=${twitterAccessToken}
TWITTER_ACCESS_TOKEN_SECRET=${twitterAccessTokenSecret}

# LinkedIn API Configuration
LINKEDIN_CLIENT_ID=${linkedinClientId}
LINKEDIN_CLIENT_SECRET=${linkedinClientSecret}
LINKEDIN_REDIRECT_URI=http://localhost:${port}/auth/linkedin/callback

# Database Configuration
DATABASE_PATH=./data/scheduler.db

# File Upload Configuration
UPLOAD_PATH=./uploads
MAX_FILE_SIZE=5242880

# Security
SESSION_SECRET=${sessionSecret}

# Scheduling Configuration
SCHEDULER_INTERVAL=60000
RETRY_ATTEMPTS=3
RETRY_DELAY=300000
`;

  fs.writeFileSync('.env', envContent);
  console.log('✓ Created .env file');
}

async function initializeDatabase() {
  console.log('\n=== Database Setup ===');
  
  const dbPath = './data/scheduler.db';
  
  if (fs.existsSync(dbPath)) {
    const overwrite = await question('Database already exists. Reset it? (y/N): ');
    if (overwrite.toLowerCase() === 'y') {
      fs.unlinkSync(dbPath);
      console.log('✓ Removed existing database');
    } else {
      console.log('Keeping existing database.');
      return;
    }
  }
  
  const db = new sqlite3.Database(dbPath);
  
  console.log('Creating database tables...');
  
  await new Promise((resolve, reject) => {
    db.serialize(() => {
      // Posts table
      db.run(`
        CREATE TABLE posts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          content TEXT NOT NULL,
          platforms TEXT NOT NULL,
          scheduled_time DATETIME NOT NULL,
          status TEXT DEFAULT 'scheduled',
          series_id INTEGER,
          series_order INTEGER,
          media_path TEXT,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          posted_at DATETIME,
          error_message TEXT,
          retry_count INTEGER DEFAULT 0
        )
      `, (err) => {
        if (err) reject(err);
        else console.log('✓ Created posts table');
      });
      
      // Series table
      db.run(`
        CREATE TABLE series (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          platforms TEXT NOT NULL,
          interval_minutes INTEGER NOT NULL,
          start_time DATETIME NOT NULL,
          status TEXT DEFAULT 'scheduled',
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => {
        if (err) reject(err);
        else console.log('✓ Created series table');
      });
      
      // Social accounts table
      db.run(`
        CREATE TABLE social_accounts (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          platform TEXT NOT NULL,
          username TEXT,
          access_token TEXT,
          refresh_token TEXT,
          expires_at DATETIME,
          is_active BOOLEAN DEFAULT 1,
          created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
      `, (err) => {
        if (err) reject(err);
        else console.log('✓ Created social_accounts table');
      });
      
      // Posting history table
      db.run(`
        CREATE TABLE posting_history (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          post_id INTEGER,
          platform TEXT NOT NULL,
          status TEXT NOT NULL,
          response_data TEXT,
          error_message TEXT,
          posted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
          FOREIGN KEY (post_id) REFERENCES posts (id)
        )
      `, (err) => {
        if (err) reject(err);
        else {
          console.log('✓ Created posting_history table');
          resolve();
        }
      });
    });
  });
  
  db.close();
  console.log('✓ Database setup complete');
}

async function createGitIgnore() {
  console.log('\n=== Git Configuration ===');
  
  const gitignoreContent = `# Dependencies
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Database
data/*.db
data/*.db-journal

# Logs
logs/
*.log

# Uploads
uploads/*
!uploads/.gitkeep

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# IDE
.vscode/
.idea/
*.swp
*.swo

# Temporary files
*.tmp
*.temp
`;

  fs.writeFileSync('.gitignore', gitignoreContent);
  console.log('✓ Created .gitignore file');
  
  // Create .gitkeep for uploads directory
  fs.writeFileSync('./uploads/.gitkeep', '');
  console.log('✓ Created uploads/.gitkeep');
}

async function main() {
  console.log('🚀 Social Media Scheduler Setup\n');
  console.log('This script will help you set up your social media scheduling app.\n');
  
  try {
    await createDirectories();
    await setupEnvironment();
    await initializeDatabase();
    await createGitIgnore();
    
    console.log('\n🎉 Setup complete!');
    console.log('\nNext steps:');
    console.log('1. Run "npm install" to install dependencies');
    console.log('2. Run "npm start" to start the application');
    console.log('3. Open http://localhost:3000 in your browser');
    console.log('\nFor scheduling to work automatically, also run:');
    console.log('   npm run scheduler');
    console.log('\nSee README.md for more detailed instructions.');
    
  } catch (error) {
    console.error('\n❌ Setup failed:', error.message);
    process.exit(1);
  } finally {
    rl.close();
  }
}

if (require.main === module) {
  main();
}

module.exports = { createDirectories, setupEnvironment, initializeDatabase };